[TT-10317] Add charts metadata
TykTechnologies/tyk-charts pull request #147
Opened 2023-10-30 09:57 UTC by komalsukhani

## Description

Added following information in all the charts
1. home
2. sources
3. keywords
4. [artifacts hub category ](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations)

## Related Issue

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-30 11:39 UTC, buraksekili approved these changes
perfect! thank you

2023-10-30 22:52 UTC, caroltyk requested changes

2023-10-30 22:52 UTC, caroltyk commented on tyk-data-plane/Chart.yaml
Chart Description:
tyk-data-plane provides the default deployment of a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB control plane. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pump, an analytics purger that moves the data generated by your Tyk gateways to any back-end. Furthermore, it has all the required modifications to easily connect to Tyk Cloud or Multi Data Center (MDCB) control plane.

2023-10-30 22:52 UTC, caroltyk commented on tyk-data-plane/Chart.yaml
> +  - https://tyk.io/docs/
please update source URL to exact chart URL
please move other links to annotations

2023-10-30 22:52 UTC, caroltyk commented on tyk-oss/Chart.yaml
> +  - https://tyk.io/docs/
please update source URL to exact chart URL
please move other links to annotations

2023-10-30 22:52 UTC, caroltyk commented on tyk-oss/Chart.yaml
> +  - edge gateway
```suggestion
  - api gateway
  - reverse proxy
  - api management
  - ingress
  - ingress controller
  - open source gateway
  - edge gateway
  - tyk
  - tyk gateway
  - tyk open source
```

2023-10-30 22:52 UTC, caroltyk commented on tyk-stack/Chart.yaml
> +  - edge gateway
```suggestion
  - api gateway
  - reverse proxy
  - api management
  - tyk
  - tyk stack
  - tyk self managed
  - apis
  - api developer portal
```

2023-10-30 22:52 UTC, caroltyk commented on tyk-stack/Chart.yaml
Chart Description:
tyk-stack provides the default deployment of Tyk Self Managed on a cluster. It will deploy all required Tyk components with the settings provided in the values.yaml file. It includes: Tyk Gateway, an open source Enterprise API Gateway (supporting REST, GraphQL, TCP and gRPC protocols). Tyk Pump, an analytics purger that moves the data generated by your Tyk nodes to any back-end. Furthermore, it has all the required modifications to easily connect to Tyk Cloud or Multi Data Center (MDCB) control plane. Tyk Dashboard, a license based component that provides GUI management interface and analytics platform for Tyk. Tyk Developer Enterprise Portal, a full-fledged CMS-like system for API providers to publish, monetise and drive the adoption of APIs.

2023-10-30 22:52 UTC, caroltyk commented on tyk-data-plane/Chart.yaml
Chart Description:
tyk-data-plane provides the default deployment of a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB control plane. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pump, an analytics purger that moves the data generated by your Tyk gateways to any back-end. Furthermore, it has all the required modifications to easily connect to Tyk Cloud or Multi Data Center (MDCB) control plane.

2023-10-30 22:52 UTC, caroltyk commented on tyk-data-plane/Chart.yaml
> +  - https://tyk.io/docs/
same as above

2023-10-31 06:55 UTC, komalsukhani commented on tyk-stack/Chart.yaml
@caroltyk Should I remove this line `Furthermore, it has all the required modifications to easily connect to Tyk Cloud or Multi Data Center (MDCB) control plane.` ?

2023-10-31 08:33 UTC, caroltyk commented on tyk-oss/Chart.yaml
Description:
Tyk-oss provides the default deployment of the Tyk Open Source stack. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pump, an analytics purger that moves the data generated by your Tyk gateways to any back-end.

2023-10-31 08:35 UTC, caroltyk commented on components/tyk-gateway/Chart.yaml
>  description: This chart deploys the open source Tyk Gateway.
```suggestion
description: A Helm chart for deploying the open source Tyk Gateway.
```

2023-10-31 08:36 UTC, caroltyk commented on components/tyk-pump/Chart.yaml
>  description: This chart deploys the open source Tyk Pump.
```suggestion
description: A Helm chart for deploying the open source Tyk Pump.
```

2023-10-31 08:37 UTC, caroltyk commented on tyk-data-plane/Chart.yaml
> +  Chart provides the default deployment of a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users.
```suggestion
A Helm chart for deploying a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users.
```

2023-10-31 08:37 UTC, caroltyk commented on tyk-stack/Chart.yaml
> +  Chart provides the default deployment of Tyk Self Managed on a cluster.
```suggestion
A Helm chart for deploying Tyk Self Managed stack on a cluster.
```

2023-10-31 08:38 UTC, caroltyk commented on tyk-stack/Chart.yaml
> +  It includes:
```suggestion
  It includes:
```

2023-10-31 08:38 UTC, caroltyk requested changes
Further comments

2023-10-31 13:27 UTC, caroltyk approved these changes
💯 thank you @komalsukhani

2023-11-01 06:41 UTC, merged