TT-10579, adapted misleading component flags
TykTechnologies/tyk-charts pull request #179
Opened 2023-11-22 11:09 UTC by andrei-tyk

## Description

Removed the global.components.dashboard flag as it was misleading and adapted the gateway to use a gateway-specific flag

## Related Issue

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-11-22 11:35 UTC, komalsukhani approved these changes

2023-11-23 00:10 UTC, caroltyk requested changes
This line should be updated too https://github.com/TykTechnologies/tyk-charts/blob/8bdd947174eacc2719f69afece5faabcaeaee7fd/components/tyk-gateway/templates/deployment-gw-repset.yaml#L155C58-L155C58

2023-11-23 07:38 UTC, komalsukhani requested changes

2023-11-23 08:54 UTC, caroltyk approved these changes

2023-11-23 17:21 UTC, merged