TT-10903: update gateway and dashboard haskeys values
TykTechnologies/tyk-charts pull request #208
Opened 2024-01-04 11:21 UTC by olamilekan000

## Description

```
Change moves the haskeys value to the global section for Gateway and Dashboard component charts.
```

## Related Issue

https://tyktech.atlassian.net/browse/TT-10903

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-16 06:04 UTC, komalsukhani requested changes

2024-01-16 06:04 UTC, komalsukhani commented on components/tyk-gateway/templates/deployment-gw-repset.yaml
> +            value: {{ .Values.global.hashKeys | toString | default "true" | quote }}
No need to set the default value here. It should be enough if we set it to true in default values.yaml

2024-01-16 06:04 UTC, komalsukhani commented on tyk-stack/values.yaml
> -    # hashKeys specifies that if your Tyk Gateway is using hashed keys, set this value to true so it matches.
We still need this for backward compatibility.

2024-01-16 06:04 UTC, komalsukhani commented on tyk-stack/values.yaml
> +  # It is used to set TYK_DB_HASHKEYS
Can you also mention that this will take precedence over `dashboard.hashKeys` and will enable hashKeys for all the components.

2024-01-16 06:04 UTC, komalsukhani commented on tyk-stack/values.yaml
We will also need to update tyk-oss chart.

2024-01-16 15:09 UTC, olamilekan000 commented on tyk-stack/values.yaml
I don't seem to find any values for `hashkeys` in it. Kindly direct me to it. Thanks

2024-01-17 06:33 UTC, komalsukhani requested changes

2024-01-17 06:33 UTC, komalsukhani commented on components/tyk-gateway/values.yaml
> +  # hashKeys is used to enable/disable key hashing. It should match with the value set in Gateway configuration.
```suggestion
  # hashKeys is used to enable/disable key hashing.
```

2024-01-17 06:33 UTC, komalsukhani commented on components/tyk-gateway/values.yaml
> +  # The Dashboard will now operate in a mode that is compatible with key hashing.
We can delete this line as it's not relevant to gateway.

2024-01-17 06:33 UTC, komalsukhani commented on tyk-stack/values.yaml
You need to make new entry in global section for tyk-oss like you have done it in tyk-stack.

2024-01-17 06:33 UTC, komalsukhani commented on tyk-stack/values.yaml
> +  # It is used to set TYK_DB_HASHKEYS
It will enable hashkeys in both gateway and dashboard. Can you update the comment accordingly?

2024-01-17 13:45 UTC, komalsukhani approved these changes

2024-01-19 09:50 UTC, komalsukhani approved these changes

2024-01-19 11:48 UTC, merged