TT-10821: add support for analytics on MDCB
TykTechnologies/tyk-charts pull request #242
Opened 2024-03-04 04:10 UTC by olamilekan000

## Description

```
change adds support for analytics on MDCB
```

## Related Issue

https://tyktech.atlassian.net/browse/TT-10821

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-03-05 07:41 UTC, komalsukhani commented on components/tyk-pump/templates/deployment-pmp.yaml
> +          - name: TYK_MDCB_FORWARDANALYTICSTOPUMP
This is MDCB environment variable. If pump is enabled(global.components.pump), then this should be set to true.

2024-03-07 07:21 UTC, komalsukhani requested changes

2024-03-07 07:21 UTC, komalsukhani commented on components/tyk-pump/values.yaml
> +    # This wiil abllow tyk-pump to pull analytics from Redis and send to your own data sinks.
```suggestion
    # This will allow tyk-pump to pull analytics from Redis and send to your own data sinks.
```

2024-03-07 07:21 UTC, komalsukhani commented on components/tyk-pump/values.yaml
> +    # If this is enabled TYK_MDCB_FORWARDANALYTICSTOPUMP will also be enabled.
Please remove this.

2024-03-07 07:28 UTC, komalsukhani commented on components/tyk-pump/values.yaml
> +    # This wiil allow tyk-pump to pull analytics from Redis and send to your own data sinks.
```suggestion
    # This will allow tyk-pump to pull analytics from Redis and send to your own data sinks.
```

2024-03-07 07:28 UTC, komalsukhani approved these changes

2024-04-10 12:57 UTC, merged

2024-04-30 13:44 UTC, caroltyk commented on tyk-control-plane/values.yaml
> +    storeAnalyticsPerMinute: true
Is it intentional to set to true in control plane chart?