Update NOTES.txt
TykTechnologies/tyk-charts pull request #270
Opened 2024-04-22 15:31 UTC by caroltyk

## Description

Update control plane installation notes for

1. Explicit how to set connection string in tyk-data-plane
2. Suggest a few variables about how to get MDCB connection string dependent on service type

## Related Issue

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-24 13:32 UTC, komalsukhani requested changes

2024-04-24 13:32 UTC, komalsukhani commented on tyk-control-plane/templates/NOTES.txt
> +If data plane is deployed in the same cluster, it can be accessed via this connection string:
```suggestion
If data plane is deployed in the same cluster, MDCB can be accessed via this connection string:
```

2024-04-24 13:32 UTC, komalsukhani commented on tyk-control-plane/templates/NOTES.txt
> +  export NODE_IP=$(kubectl get nodes --namespace {{ .Release.Namespace }} -o jsonpath="{.items[0].status.addresses[0].address}")
```suggestion
  export NODE_IP=$(kubectl get nodes -o jsonpath="{.items[0].status.addresses[0].address}")
```

2024-04-24 13:32 UTC, komalsukhani commented on tyk-control-plane/templates/NOTES.txt
> +           You can watch the status of by running 'kubectl get --namespace {{ .Release.Namespace }} svc -w {{ $tykMDCBFullName }}'
```suggestion
           You can watch the status of service by running 'kubectl get --namespace {{ .Release.Namespace }} svc -w {{ $tykMDCBSvc}}'
```

2024-04-24 13:32 UTC, komalsukhani commented on tyk-control-plane/templates/NOTES.txt
> +  export MDCB_CONNECTIONSTRING=$SERVICE_IP:{{ index .Values "tyk-mdcb" "mdcb" "service" "port" }}
```suggestion
  export MDCB_CONNECTIONSTRING=$SERVICE_IP:{{ $tykMDCBSvcPort }}
```

2024-04-26 15:00 UTC, caroltyk commented
changes applied

2024-05-06 11:29 UTC, komalsukhani approved these changes

2024-05-06 11:29 UTC, merged