(ci): add workflow for alpha Helm chart releases
TykTechnologies/tyk-charts pull request #371
Opened 2024-12-13 12:40 UTC by buraksekili

## Description

This PR introduces a new GitHub Actions workflow that automates the release process for alpha versions of our Helm charts. The workflow is triggered when a tag matching the pattern `vX.Y.Z-alpha.N` is pushed to the repository.

- Automatically detects all Helm charts in the repository (excluding `tyk-operator`)
- Updates chart versions to match the release tag
- Adds alpha prerelease annotations for ArtifactHub
- Updates internal chart dependencies to maintain version consistency
- Runs validation checks before packaging

## Related Issue

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-12-16 06:30 UTC, komalsukhani requested changes

2024-12-16 06:31 UTC, buraksekili commented on .github/workflows/release-alpha.yaml
> +      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
It is possible but needs a bit of modification to handle tyk-operator release.

2024-12-16 21:23 UTC, olamilekan000 approved these changes

2024-12-17 05:55 UTC, komalsukhani approved these changes

2024-12-17 05:55 UTC, komalsukhani commented
@buraksekili Merging the PR directly as it doesn't need QA.

2024-12-17 05:55 UTC, merged